/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Praneeth' at '30/04/16 11:42 AM' with Gradle 2.13
 *
 * @author Praneeth, @date 30/04/16 11:42 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
